import { AppState, Task, Defect, UserStory, Release, TeamMember } from '../types';
import { formatDisplayDate, formatLongDate, isToday, formatTime12 } from '../utils/date';

export function buildStandupEmail(state: AppState): {
  subject: string;
  html: string;
  markdown: string;
  mailtoUrl: string;
} {
  const dateFormatted = formatLongDate(state.dateStr);
  const subject = `[Standup] Northstar Delivery Summary — ${formatDisplayDate(state.dateStr)}`;
  
  const entriesList = Object.entries(state.standup)
    .filter(([_, entry]) => entry.yesterday || entry.today || entry.blockers)
    .map(([memberId, entry]) => {
      const member = state.team.find(t => t.id === memberId);
      const name = member ? member.name : 'Team Member';
      const role = member ? member.role : '';
      return {
        name,
        role,
        ...entry
      };
    });

  // Today's tasks
  const todayTasks = state.tasks.filter(t => t.dateStr === state.dateStr);
  const highPriority = todayTasks.filter(t => t.priority === 'high');
  const completedCount = todayTasks.filter(t => t.status === 'complete').length;

  // Markdown format
  let md = `# Northstar Delivery — Daily Standup Digest\n`;
  md += `**Date:** ${dateFormatted}\n`;
  md += `**Progress:** ${completedCount}/${todayTasks.length} tasks completed today\n\n`;

  if (entriesList.length > 0) {
    md += `## 👥 Team Updates\n\n`;
    entriesList.forEach(e => {
      md += `### ${e.name} (${e.role})\n`;
      if (e.yesterday) md += `- **Yesterday:** ${e.yesterday}\n`;
      if (e.today) md += `- **Today:** ${e.today}\n`;
      if (e.blockers && e.blockers.toLowerCase() !== 'none') {
        md += `- 🚨 **Blockers:** ${e.blockers}\n`;
      }
      md += `\n`;
    });
  }

  if (highPriority.length > 0) {
    md += `## 🎯 Critical & High Priority Focus\n\n`;
    highPriority.forEach(t => {
      const icon = t.status === 'complete' ? '[x]' : t.status === 'partial' ? '[-]' : '[ ]';
      const timeStr = t.time ? ` (${formatTime12(t.time)})` : '';
      md += `- ${icon} ${t.title}${timeStr}\n`;
    });
    md += `\n`;
  }

  // HTML format
  let html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #15221E; max-width: 680px; margin: 0 auto; padding: 24px; background: #FFFFFF; border-radius: 12px; border: 1px solid #E2E8E4;">
      <div style="border-bottom: 2px solid #0C6E5E; padding-bottom: 16px; margin-bottom: 20px;">
        <h2 style="margin: 0 0 4px; color: #0C6E5E; font-size: 20px;">Northstar Delivery — Daily Standup</h2>
        <p style="margin: 0; color: #5A675F; font-size: 13px;">${dateFormatted} &bull; ${completedCount}/${todayTasks.length} daily commitments completed</p>
      </div>

      ${entriesList.map(e => `
        <div style="margin-bottom: 20px; background: #F7FAF8; padding: 14px 18px; border-radius: 8px; border-left: 3px solid #0C6E5E;">
          <h4 style="margin: 0 0 8px; font-size: 15px; color: #15221E;">${e.name} <span style="font-size: 12px; color: #84918A; font-weight: normal;">— ${e.role}</span></h4>
          ${e.yesterday ? `<p style="margin: 4px 0; font-size: 13px;"><strong>Yesterday:</strong> ${e.yesterday}</p>` : ''}
          ${e.today ? `<p style="margin: 4px 0; font-size: 13px;"><strong>Today:</strong> ${e.today}</p>` : ''}
          ${e.blockers && e.blockers.toLowerCase() !== 'none' ? `<p style="margin: 4px 0; font-size: 13px; color: #B42318;"><strong>🚨 Blockers:</strong> ${e.blockers}</p>` : ''}
        </div>
      `).join('')}

      <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid #E2E8E4; font-size: 12px; color: #84918A;">
        Generated by Northstar Delivery &bull; Real-time client delivery & team operations
      </div>
    </div>
  `;

  const recipient = state.settings.emailRecipient || state.settings.managerEmail || '';
  const bodyEncoded = encodeURIComponent(md);
  const subjectEncoded = encodeURIComponent(subject);
  const mailtoUrl = `mailto:${recipient}?subject=${subjectEncoded}&body=${bodyEncoded}`;

  return { subject, html, markdown: md, mailtoUrl };
}

export function buildQaStatusReport(state: AppState, releaseId?: string): {
  subject: string;
  html: string;
  markdown: string;
  mailtoUrl: string;
} {
  const currentRelease = state.releases.find(r => r.id === (releaseId || state.selectedReleaseId)) || state.releases[0];
  const releaseName = currentRelease ? currentRelease.name : 'All Releases';
  const targetDate = currentRelease ? currentRelease.targetDate : 'TBD';

  const relStories = currentRelease 
    ? state.userStories.filter(s => s.releaseId === currentRelease.id)
    : state.userStories;

  const relDefects = currentRelease
    ? state.defects.filter(d => d.releaseId === currentRelease.id)
    : state.defects;

  const passedStories = relStories.filter(s => s.status === 'QA Passed' || s.status === 'Done');
  const inQaStories = relStories.filter(s => s.status === 'QA In Progress' || s.status === 'QA Ready');
  const blockedStories = relStories.filter(s => s.status === 'Blocked');

  const criticalDefects = relDefects.filter(d => d.severity === 'critical' && d.status !== 'Closed');
  const highDefects = relDefects.filter(d => d.severity === 'high' && d.status !== 'Closed');
  const openDefects = relDefects.filter(d => d.status !== 'Closed');

  const subject = `[QA Status] ${releaseName} — Health & Defect Gate (${formatDisplayDate(state.dateStr)})`;

  let md = `# QA & Release Status Report: ${releaseName}\n`;
  md += `**Report Date:** ${formatLongDate(state.dateStr)}\n`;
  md += `**Target Launch Date:** ${targetDate}\n`;
  md += `**Release Status:** ${currentRelease?.status || 'Active QA'}\n\n`;

  md += `## 📊 Executive Summary & Health Metrics\n`;
  md += `- **Story QA Pass Rate:** ${passedStories.length}/${relStories.length} (${relStories.length ? Math.round((passedStories.length / relStories.length) * 100) : 0}%)\n`;
  md += `- **Active Open Defects:** ${openDefects.length} (🚨 ${criticalDefects.length} Critical, ⚠️ ${highDefects.length} High)\n`;
  md += `- **Blocked Work Items:** ${blockedStories.length}\n\n`;

  if (criticalDefects.length > 0) {
    md += `## 🚨 Critical Defect Blockers (Action Required)\n`;
    criticalDefects.forEach(d => {
      const assignee = state.team.find(t => t.id === d.assigneeId)?.name || 'Unassigned';
      md += `- **[DEF-${d.adoId || d.id}]** ${d.title} (Status: ${d.status}, Assignee: ${assignee})\n`;
    });
    md += `\n`;
  }

  md += `## 🧪 User Story Validation Progress\n`;
  relStories.forEach(s => {
    const assignee = state.team.find(t => t.id === s.assigneeId)?.name || 'Unassigned';
    md += `- [${s.status}] **US-${s.adoId || s.id}:** ${s.title} (${s.storyPoints || 0} pts, Assignee: ${assignee})\n`;
  });

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #15221E; max-width: 680px; margin: 0 auto; padding: 24px; background: #FFFFFF; border-radius: 12px; border: 1px solid #E2E8E4;">
      <div style="border-bottom: 2px solid #0C6E5E; padding-bottom: 16px; margin-bottom: 20px;">
        <h2 style="margin: 0 0 4px; color: #0C6E5E; font-size: 20px;">QA & Release Gate Status: ${releaseName}</h2>
        <p style="margin: 0; color: #5A675F; font-size: 13px;">Target: ${targetDate} &bull; Stories Passed: ${passedStories.length}/${relStories.length}</p>
      </div>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 20px;">
        <div style="background: #F7FAF8; padding: 12px; border-radius: 8px; border: 1px solid #E2E8E4; text-align: center;">
          <div style="font-size: 20px; font-weight: bold; color: #0C6E5E;">${passedStories.length}/${relStories.length}</div>
          <div style="font-size: 11px; color: #84918A;">User Stories Verified</div>
        </div>
        <div style="background: #FFFDFD; padding: 12px; border-radius: 8px; border: 1px solid #F8D7DA; text-align: center;">
          <div style="font-size: 20px; font-weight: bold; color: #B42318;">${openDefects.length}</div>
          <div style="font-size: 11px; color: #B42318;">Open Defects (${criticalDefects.length} Crit)</div>
        </div>
      </div>

      ${criticalDefects.length > 0 ? `
        <div style="background: #F8ECEC; border: 1px solid #F8D7DA; padding: 14px; border-radius: 8px; margin-bottom: 20px;">
          <h4 style="margin: 0 0 8px; color: #9B1D32; font-size: 14px;">🚨 Critical Blockers</h4>
          ${criticalDefects.map(d => `<p style="margin: 4px 0; font-size: 12px; color: #9B1D32;">&bull; <strong>DEF-${d.adoId || d.id}:</strong> ${d.title}</p>`).join('')}
        </div>
      ` : ''}

      <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid #E2E8E4; font-size: 12px; color: #84918A;">
        Generated by Northstar Delivery &bull; QA Test Sanity Engine
      </div>
    </div>
  `;

  const recipient = state.settings.emailRecipient || state.settings.managerEmail || '';
  const mailtoUrl = `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(md)}`;

  return { subject, html, markdown: md, mailtoUrl };
}

export function buildDashboardDigest(state: AppState): {
  subject: string;
  html: string;
  markdown: string;
  mailtoUrl: string;
} {
  const dateFormatted = formatLongDate(state.dateStr);
  const subject = `[Delivery Pulse] Northstar Comprehensive Operations — ${formatDisplayDate(state.dateStr)}`;

  const todayTasks = state.tasks.filter(t => t.dateStr === state.dateStr);
  const doneTasks = todayTasks.filter(t => t.status === 'complete');
  const highPending = todayTasks.filter(t => t.priority === 'high' && t.status !== 'complete');

  let md = `# Northstar Delivery Pulse: Full Operations Digest\n`;
  md += `**Date:** ${dateFormatted}\n\n`;
  md += `## 🚀 Today's Task Execution\n`;
  md += `- **Completed:** ${doneTasks.length}/${todayTasks.length} tasks\n`;
  md += `- **High Priority Pending:** ${highPending.length}\n\n`;

  md += `## 📋 Backlog & Defects Overview\n`;
  md += `- **Active User Stories:** ${state.userStories.filter(s => s.status !== 'Done').length}\n`;
  md += `- **Open Defects:** ${state.defects.filter(d => d.status !== 'Closed').length}\n`;
  md += `- **Releases in Flight:** ${state.releases.filter(r => r.status === 'Active QA' || r.status === 'Staging').length}\n`;

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #15221E; max-width: 680px; margin: 0 auto; padding: 24px; background: #FFFFFF; border-radius: 12px; border: 1px solid #E2E8E4;">
      <div style="border-bottom: 2px solid #0C6E5E; padding-bottom: 16px; margin-bottom: 20px;">
        <h2 style="margin: 0 0 4px; color: #0C6E5E; font-size: 20px;">Northstar Delivery Pulse</h2>
        <p style="margin: 0; color: #5A675F; font-size: 13px;">${dateFormatted}</p>
      </div>

      <p style="font-size: 13px; margin-bottom: 16px;"><strong>Tasks Progress:</strong> ${doneTasks.length}/${todayTasks.length} completed.</p>
      <p style="font-size: 13px; margin-bottom: 16px;"><strong>Active User Stories:</strong> ${state.userStories.length} tracked across ${state.releases.length} releases.</p>
      <p style="font-size: 13px; margin-bottom: 16px;"><strong>Defect Count:</strong> ${state.defects.filter(d => d.status !== 'Closed').length} active defects.</p>

      <div style="margin-top: 24px; padding-top: 16px; border-top: 1px solid #E2E8E4; font-size: 12px; color: #84918A;">
        Generated by Northstar Delivery Hub
      </div>
    </div>
  `;

  const recipient = state.settings.emailRecipient || '';
  const mailtoUrl = `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(md)}`;

  return { subject, html, markdown: md, mailtoUrl };
}
