import React, { useState } from 'react';
import { 
  X, 
  Sparkles, 
  RotateCw, 
  CheckCircle2, 
  AlertTriangle, 
  Layers, 
  FileCode, 
  ArrowRight,
  Zap
} from 'lucide-react';
import { ApiAutomationCollection, ApiRequestItem } from '../../types/apiAutomation';
import { generateId } from '../../utils/date';

interface AiSuiteGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuiteGenerated: (newCollection: ApiAutomationCollection) => void;
}

export const AiSuiteGeneratorModal: React.FC<AiSuiteGeneratorModalProps> = ({
  isOpen,
  onClose,
  onSuiteGenerated
}) => {
  const [prompt, setPrompt] = useState<string>('');
  const [endpointSpec, setEndpointSpec] = useState<string>('');
  const [userStoryTitle, setUserStoryTitle] = useState<string>('ACM-8420: Cellular & Wi-Fi Session Profile Synchronization');
  const [category, setCategory] = useState<'smoke' | 'regression' | 'security' | 'integration'>('smoke');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const res = await fetch('/api/automation/generate-suite', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt,
          endpointSpec,
          userStoryTitle,
          category
        })
      });

      const data = await res.json();
      if (!res.ok || !data.ok) {
        throw new Error(data.error || 'Failed to generate API suite with AI.');
      }

      const generatedSuite = data.suite;
      const completeCollection: ApiAutomationCollection = {
        id: generateId('col'),
        name: generatedSuite.name || 'AI Generated Automation Suite',
        description: generatedSuite.description || 'Generated by Gemini AI Automation Architect',
        category: generatedSuite.category || category,
        baseUrl: generatedSuite.baseUrl || '{{baseUrl}}',
        variables: generatedSuite.variables || { baseUrl: 'http://localhost:3000' },
        webhookToken: `whk_${generateId('')}`,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        requests: (generatedSuite.requests || []).map((r: any, idx: number) => ({
          id: generateId('req'),
          name: r.name || `Step ${idx + 1}`,
          method: r.method || 'GET',
          url: r.url || '{{baseUrl}}/api/health',
          description: r.description || '',
          headers: r.headers || [{ key: 'Content-Type', value: 'application/json', enabled: true }],
          params: r.params || [],
          bodyType: r.bodyType || 'none',
          bodyContent: r.bodyContent || '',
          assertions: (r.assertions || []).map((a: any) => ({
            id: generateId('as'),
            type: a.type || 'status_code',
            operator: a.operator || 'equals',
            expectedValue: String(a.expectedValue || '200'),
            description: a.description || 'Status is 200 OK',
            enabled: true
          })),
          extractVariables: (r.extractVariables || []).map((ex: any) => ({
            id: generateId('ex'),
            source: ex.source || 'json_body',
            path: ex.path || 'token',
            variableName: ex.variableName || 'authToken',
            enabled: true,
            description: ex.description || 'Extracted variable'
          })),
          enabled: true,
          timeoutMs: r.timeoutMs || 3000
        }))
      };

      onSuiteGenerated(completeCollection);
      onClose();
    } catch (err: any) {
      setError(err.message || 'AI generation failed. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in duration-150">
      <div 
        className="bg-[var(--surface)] border border-[var(--border)] rounded-2xl shadow-2xl w-full max-w-2xl overflow-hidden animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-6 py-4 border-b border-[var(--border)] flex items-center justify-between bg-[var(--surface-hover)]/40 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-purple-500 to-indigo-600 text-white flex items-center justify-center shadow-sm">
              <Sparkles size={18} />
            </div>
            <div>
              <h2 className="text-sm font-extrabold text-[var(--text-primary)]">
                AI API Suite & Assertion Generator
              </h2>
              <p className="text-[11px] text-[var(--text-muted)]">
                Powered by Gemini AI to synthesize end-to-end API test workflows and assertions
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--surface)] transition-colors cursor-pointer"
          >
            <X size={18} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4 max-h-[75vh] overflow-y-auto">
          {error && (
            <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-600 dark:text-rose-400 text-xs flex items-start gap-2">
              <AlertTriangle size={15} className="shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          <div className="space-y-1.5">
            <label className="text-xs font-bold text-[var(--text-primary)]">User Story or Feature Context</label>
            <input
              type="text"
              value={userStoryTitle}
              onChange={(e) => setUserStoryTitle(e.target.value)}
              placeholder="e.g. ACM-8420: Cellular & Wi-Fi Session Profile Synchronization"
              className="w-full px-3 py-2 rounded-xl border border-[var(--border)] bg-[var(--bg-subtle)] text-xs font-bold text-[var(--text-primary)] focus:border-[var(--primary)] focus:outline-hidden"
            />
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-bold text-[var(--text-primary)]">Test Suite Category</label>
            <div className="grid grid-cols-4 gap-2">
              {(['smoke', 'regression', 'security', 'integration'] as const).map(cat => (
                <button
                  key={cat}
                  type="button"
                  onClick={() => setCategory(cat)}
                  className={`py-2 px-2.5 rounded-xl text-xs font-bold capitalize transition-all cursor-pointer border ${
                    category === cat
                      ? 'bg-[var(--primary)] text-white border-[var(--primary)] shadow-xs'
                      : 'bg-[var(--surface)] hover:bg-[var(--surface-hover)] border-[var(--border)] text-[var(--text-secondary)]'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-bold text-[var(--text-primary)]">API Endpoints or OpenAPI Excerpt (Optional)</label>
            <textarea
              value={endpointSpec}
              onChange={(e) => setEndpointSpec(e.target.value)}
              rows={4}
              placeholder="POST /api/v1/auth/login { username, password } -> returns { token }&#10;GET /api/v1/profile (Bearer token) -> returns { user, quota }"
              className="w-full p-3 rounded-xl border border-[var(--border)] bg-[var(--bg-subtle)] text-xs font-mono text-[var(--text-primary)] focus:border-[var(--primary)] focus:outline-hidden"
            />
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-bold text-[var(--text-primary)]">Specific Test Requirements or Edge Cases (Optional)</label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={3}
              placeholder="Verify expired token 401 response, invalid JSON payload validation, latency under 400ms, and variable chaining for newly created IDs."
              className="w-full p-3 rounded-xl border border-[var(--border)] bg-[var(--bg-subtle)] text-xs text-[var(--text-primary)] focus:border-[var(--primary)] focus:outline-hidden"
            />
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-[var(--border)] bg-[var(--surface-hover)]/30 flex items-center justify-between shrink-0">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-[var(--surface)] hover:bg-[var(--surface-hover)] border border-[var(--border)] text-xs font-bold text-[var(--text-primary)] transition-all cursor-pointer shadow-xs"
          >
            Cancel
          </button>
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="px-5 py-2 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white text-xs font-bold transition-all shadow-md flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
          >
            {isGenerating ? <RotateCw className="animate-spin" size={14} /> : <Sparkles size={14} />}
            <span>{isGenerating ? 'Synthesizing Test Suite...' : 'Generate API Suite'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
